[mgr]
sort_by = "alphabetical"
sort_sensitive = true
sort_dir_first = true
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true

[preview]
tab_size = 200


[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },
	{ name = "*.mp3", use = "play" },
	{ name = "*.mp4", use = "watch" },
	{ name = "*.avi", use = "watch" },
	{ name = "*.mov", use = "watch" },
	{ name = "*.pdf", use = "read" },
]

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpg123 "$@"', block = true, for = "unix" },
]
watch = [
	{ run = 'vlc "$@"', block = true, desc = "Open a video" },
]
read = [
  { run = 'sioyek "$@"', block = true, for = "unix" }
]
open = [
  { run = 'libreoffice "$@"', block = true, for = "unix" }
]
