[manager]
sort_by = "modified"
sort_sensitive = true
sort_dir_first = true
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true

[preview]
tab_size = 200

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
